### ISSUE TITLE
Module Not Working

### ISSUE THREAD

**Issue by ranu7455** [PHOENIX-MEDIA/Magento2-CashOnDelivery#12]
Am unable to install the module in magento.
My version of magento is 2.2.2 community edition ( after running the setup upgrade command the module doesn't show up in admin panel.

Kindly help

**Comment by josecoelho509** [comment]
Hello

 

You already saw in stores à Configuration à Sales à Payment Methods / Other Payments Methods

 

that's where it used to be.

 

If it is not tell me step by step how you did the installation included the commands that you did in ssh.

 

 

De: ranu7455 [mailto:notifications@github.com] 
Enviada: 21 de março de 2018 15:29
Para: PHOENIX-MEDIA/Magento2-CashOnDelivery
Cc: Subscribed
Assunto: [PHOENIX-MEDIA/Magento2-CashOnDelivery] Module Not Working (#12)

 

Am unable to install the module in magento.
My version of magento is 2.2.2 community edition ( after running the setup upgrade command the module doesn't show up in admin panel.

Kindly help

**Comment by ranu7455** [comment]
after downloading and unzipping the files in public_html/app/code
i used the php bin/magento setup:upgrade  command but after the same module is not yet visible in 
  Payment Methods / Other Payments Methods

**Comment by josecoelho509** [comment]
You see if the module is in app/code/Phoenix/CashOnDelivery ?

 

After, go to ssh (root directory of your magento installation)

 

Run command: php bin/magento module:show:status

See if Phoenix_CashOnDelivery is enable, if not turn enable

 

After that run that commands 

php bin/magento setup:upgrade --keep-generated

php bin/magento setup:static-content:deploy -f

php bin/magento index:reindex

php bin/magento cache:clean

php bin/magento setup:di:compile

php chmod -R 777 pub var

php chmod -R -v 777 generated

 

for me it works fine

De: ranu7455 [mailto:notifications@github.com] 
Enviada: 21 de março de 2018 15:48
Para: PHOENIX-MEDIA/Magento2-CashOnDelivery
Cc: josecoelho509; Comment
Assunto: Re: [PHOENIX-MEDIA/Magento2-CashOnDelivery] Module Not Working (#12)

 

after downloading and unzipping the files in public_html/app/code
i used the php bin/magento setup:upgrade command but after the same module is not yet visible in
Payment Methods / Other Payments Methods

**Comment by ranu7455** [comment]
Yes, its working now. 
Thanks for your kind guidance. :+1:
