### ISSUE TITLE
COD fee translation issue

### ISSUE THREAD

**Issue by zolthan** [PHOENIX-MEDIA/Magento2-CashOnDelivery#14]
In the checkout sidebar the "Cash on Delivery Fee" is not translated correctly. In the emails and backend everything is correct.

![cod-fee-translation-issue](https://user-images.githubusercontent.com/3035434/38249748-f3236a02-374c-11e8-9152-28ed230dd432.png)

**Comment by PHOENIX-MEDIA** [comment]
Fixed with #5
