### ISSUE TITLE
Installation is not being processed 

### ISSUE THREAD

**Issue by RKBerkowits** [PHOENIX-MEDIA/Magento2-CashOnDelivery#2]
Dear Team Phoenix,

  I am facing the issue in installing this module in my magento 2.1.7
Is there any possibility to download this extension via CLI command or any other way.  My web url is - https://anytimehydration.com

**Comment by PHOENIX-MEDIA** [comment]
You can download the package as compressed archive and install it manually without composer. You can also install the module via Magento Marketplace https://marketplace.magento.com/phoenix-module-cashondelivery.html

For details on the composer issue follow #4
