### ISSUE TITLE
Sort Order

### ISSUE THREAD

**Issue by ilevennet** [PHOENIX-MEDIA/Magento2-CashOnDelivery#6]
In the plugin is missing the field "Sort Order" as in other payment type that permit to sort Payment type in a list of payments.

**Comment by silversil** [comment]
Yes, if it possible to add this option would be helpful. Thank you.

**Comment by ilevennet** [comment]
Workaround is setting other payment with order:

-2 Credit Card
-1 Paypal
and Cash on delivery display under all :-)

**Comment by silversil** [comment]
Thank you for sharing

**Comment by BeSthetic** [comment]
I need this option, please.
Thanks
