### ISSUE TITLE
Compatibility with magento 2.2.2

### ISSUE THREAD

**Issue by samuelecarpene** [PHOENIX-MEDIA/Magento2-CashOnDelivery#7]
Hi i installed your module in local environment.
After some days the plugin seems to don't work anymore.
No admin panel section to configure the plugin.
How can i investigate on causes that stopped your plugin to work?

Any help is appreciated.

**Comment by zenomordiante** [comment]
What type of problem do you have?

**Comment by ilevennet** [comment]
Do you have checked Cache, compiling?

Do you have opcache actived? If yes, you could be try to invalidate cache.

**Comment by samuelecarpene** [comment]
I tried all. Plugin not show in admin panel and it is correctly installed with composer.

**Comment by ilevennet** [comment]
Do you have seen in:

Sales -> Payment Methods -> Phoenix Cash on Delivery?

![schermata 2018-02-12 alle 16 14 01](https://user-images.githubusercontent.com/1394124/36103472-a74727cc-100f-11e8-848a-7eab84f8580f.jpg)

**Comment by samuelecarpene** [comment]
@zenomordiante sorry for my mistake... I was looking into shipping methods! Thank you for your patience. 😄
