### ISSUE TITLE
Recoverable Error: Argument 3 passed to Phoenix\CashOnDelivery\Model\Total\Tax\Quote::_clearValues() must be of the type array

### ISSUE THREAD

**Issue by ghost** [PHOENIX-MEDIA/Magento2-CashOnDelivery#8]
getting this error
main.CRITICAL: Exception message: Recoverable Error: Argument 3 passed to Phoenix\CashOnDelivery\Model\Total\Tax\Quote::_clearValues() must be of the type array, object given, called in D:\wamp64\www\gutrad.2.1.11_2\vendor\phoenix\module-cashondelivery\Model\Total\Tax\Quote.php on line 94 and defined in D:\wamp64\www\gutrad.2.1.11_2\vendor\phoenix\module-cashondelivery\Model\Total\Tax\Quote.php on line 119
Trace: #0 D:\wamp64\www\gutrad.2.1.11_2\vendor\phoenix\module-cashondelivery\Model\Total\Tax\Quote.php(119): Magento\Framework\App\ErrorHandler->handler(4096, 'Argument 3 pass...', 'D:\\wamp64\\www\\g...', 119, Array)

**Comment by PHOENIX-MEDIA** [comment]
Fixed. Thank you for reporting the issue.
