### ISSUE TITLE
COD Order Status Issue

### ISSUE THREAD

**Issue by ahmadalkaid** [PHOENIX-MEDIA/Magento2-CashOnDelivery#9]
Hi Guys,

I try to set the new order status on the payment as pending, but it's processing on all new orders coming from COD.
Could you check it please.

Thanks,

**Comment by PHOENIX-MEDIA** [comment]
Hi! Thank you for reporting this issue.

As implemented, there is no support for setting a custom order status. This will be removed from the configuration to avoid confusion.
